//
//  GeneratedPluginRegistrant.m
//  Runner
//
//  Auto-generated by Flutter — do not edit.
//

#import "GeneratedPluginRegistrant.h"

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
}

@end
